"""Update interview_evaluations schema

Revision ID: 14b3eb7cc7b2
Revises: bd40680ed7ac
Create Date: 2026-06-27 13:42:55.375717

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "14b3eb7cc7b2"
down_revision: str | Sequence[str] | None = "bd40680ed7ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("checkpoint_writes_thread_id_idx", table_name="checkpoint_writes")
    op.drop_table("checkpoint_writes")
    op.drop_index("checkpoint_blobs_thread_id_idx", table_name="checkpoint_blobs")
    op.drop_table("checkpoint_blobs")
    op.drop_index("checkpoints_thread_id_idx", table_name="checkpoints")
    op.drop_table("checkpoints")
    op.drop_table("checkpoint_migrations")
    op.alter_column(
        "assessments",
        "status",
        existing_type=sa.TEXT(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "candidate_assessments",
        "resume_parse_status",
        existing_type=sa.TEXT(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "candidate_assessments",
        "status",
        existing_type=sa.TEXT(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "candidate_assessments",
        "recruiter_decision",
        existing_type=sa.TEXT(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint("uq_candidates_email", "candidates", type_="unique")
    op.drop_index("ix_candidates_email", table_name="candidates")
    op.create_index(op.f("ix_candidates_email"), "candidates", ["email"], unique=True)
    op.alter_column(
        "csv_upload_logs",
        "successful_rows",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "csv_upload_logs",
        "failed_rows",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "csv_upload_logs",
        "overall_status",
        existing_type=sa.TEXT(),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column(
        "interview_evaluations",
        sa.Column("intro_section_score", sa.Float(), nullable=False),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column("intro_section_summary", sa.Text(), nullable=False),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "intro_section_evidence", postgresql.ARRAY(sa.Text()), nullable=False
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column("overall_technical_skill_score", sa.Float(), nullable=False),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "skill_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "skill_evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column("behavioural_cultural_score", sa.Float(), nullable=False),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column("behavioural_cultural_summary", sa.Text(), nullable=False),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "behavioural_cultural_evidence", postgresql.ARRAY(sa.Text()), nullable=False
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column("communication_score", sa.Float(), nullable=False),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column("communication_summary", sa.Text(), nullable=False),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "communication_evidence", postgresql.ARRAY(sa.Text()), nullable=False
        ),
    )
    op.add_column(
        "interview_evaluations", sa.Column("overall_summary", sa.Text(), nullable=False)
    )
    op.add_column(
        "interview_evaluations",
        sa.Column("violation_evidence", postgresql.ARRAY(sa.Text()), nullable=True),
    )
    op.drop_column("interview_evaluations", "best_answer")
    op.drop_column("interview_evaluations", "behavioural_evidence")
    op.drop_column("interview_evaluations", "tone_classification_score")
    op.drop_column("interview_evaluations", "section_summaries")
    op.drop_column("interview_evaluations", "weakest_answer")
    op.drop_column("interview_evaluations", "technical_dimension_score")
    op.drop_column("interview_evaluations", "cultural_fit_score")
    op.drop_column("interview_evaluations", "cultural_fit_summary")
    op.drop_column("interview_evaluations", "behavioural_summary")
    op.drop_column("interview_evaluations", "score_evidence")
    op.drop_column("interview_evaluations", "tone_distribution")
    op.drop_column("interview_evaluations", "score_summary")
    op.drop_column("interview_evaluations", "cultural_fit_evidence")
    op.drop_column("interview_evaluations", "overall_narrative")
    op.drop_column("interview_evaluations", "behavioural_score")
    op.alter_column(
        "notification_logs",
        "delivery_status",
        existing_type=sa.TEXT(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "recruiters",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint("uq_recruiters_email", "recruiters", type_="unique")
    op.drop_index("ix_recruiters_email", table_name="recruiters")
    op.create_index(op.f("ix_recruiters_email"), "recruiters", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recruiters_email"), table_name="recruiters")
    op.create_index("ix_recruiters_email", "recruiters", ["email"], unique=False)
    op.create_unique_constraint(
        "uq_recruiters_email",
        "recruiters",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "recruiters",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "notification_logs",
        "delivery_status",
        existing_type=sa.TEXT(),
        server_default=sa.text("'SENT'::text"),
        existing_nullable=False,
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "behavioural_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column("overall_narrative", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "cultural_fit_evidence",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column("score_summary", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "tone_distribution",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "score_evidence",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "behavioural_summary", sa.TEXT(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "cultural_fit_summary", sa.TEXT(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "cultural_fit_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "technical_dimension_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "weakest_answer",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "section_summaries",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "tone_classification_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "behavioural_evidence",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "best_answer",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("interview_evaluations", "violation_evidence")
    op.drop_column("interview_evaluations", "overall_summary")
    op.drop_column("interview_evaluations", "communication_evidence")
    op.drop_column("interview_evaluations", "communication_summary")
    op.drop_column("interview_evaluations", "communication_score")
    op.drop_column("interview_evaluations", "behavioural_cultural_evidence")
    op.drop_column("interview_evaluations", "behavioural_cultural_summary")
    op.drop_column("interview_evaluations", "behavioural_cultural_score")
    op.drop_column("interview_evaluations", "skill_evidence")
    op.drop_column("interview_evaluations", "skill_summary")
    op.drop_column("interview_evaluations", "overall_technical_skill_score")
    op.drop_column("interview_evaluations", "intro_section_evidence")
    op.drop_column("interview_evaluations", "intro_section_summary")
    op.drop_column("interview_evaluations", "intro_section_score")
    op.alter_column(
        "csv_upload_logs",
        "overall_status",
        existing_type=sa.TEXT(),
        server_default=sa.text("'PROCESSING'::text"),
        existing_nullable=False,
    )
    op.alter_column(
        "csv_upload_logs",
        "failed_rows",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "csv_upload_logs",
        "successful_rows",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_candidates_email"), table_name="candidates")
    op.create_index("ix_candidates_email", "candidates", ["email"], unique=False)
    op.create_unique_constraint(
        "uq_candidates_email",
        "candidates",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "candidate_assessments",
        "recruiter_decision",
        existing_type=sa.TEXT(),
        server_default=sa.text("'PENDING'::text"),
        existing_nullable=False,
    )
    op.alter_column(
        "candidate_assessments",
        "status",
        existing_type=sa.TEXT(),
        server_default=sa.text("'INVITED'::text"),
        existing_nullable=False,
    )
    op.alter_column(
        "candidate_assessments",
        "resume_parse_status",
        existing_type=sa.TEXT(),
        server_default=sa.text("'PENDING'::text"),
        existing_nullable=False,
    )
    op.alter_column(
        "assessments",
        "status",
        existing_type=sa.TEXT(),
        server_default=sa.text("'DRAFT'::text"),
        existing_nullable=False,
    )
    op.create_table(
        "checkpoint_migrations",
        sa.Column("v", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("v", name="checkpoint_migrations_pkey"),
    )
    op.create_table(
        "checkpoints",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checkpoint_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "parent_checkpoint_id", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "checkpoint",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "thread_id", "checkpoint_ns", "checkpoint_id", name="checkpoints_pkey"
        ),
    )
    op.create_index(
        "checkpoints_thread_id_idx", "checkpoints", ["thread_id"], unique=False
    )
    op.create_table(
        "checkpoint_blobs",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("channel", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("version", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "checkpoint_ns",
            "channel",
            "version",
            name="checkpoint_blobs_pkey",
        ),
    )
    op.create_index(
        "checkpoint_blobs_thread_id_idx",
        "checkpoint_blobs",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "checkpoint_writes",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checkpoint_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("idx", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("channel", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column(
            "task_path",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "checkpoint_ns",
            "checkpoint_id",
            "task_id",
            "idx",
            name="checkpoint_writes_pkey",
        ),
    )
    op.create_index(
        "checkpoint_writes_thread_id_idx",
        "checkpoint_writes",
        ["thread_id"],
        unique=False,
    )
    # ### end Alembic commands ###
