"""model_updates

Revision ID: a26110517ed8
Revises: 0003_recruiter_tokens
Create Date: 2026-06-15 09:47:59.047090

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a26110517ed8"
down_revision: str | Sequence[str] | None = "0003_recruiter_tokens"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "answer_evaluations", sa.Column("session_id", sa.UUID(), nullable=False)
    )
    op.add_column(
        "answer_evaluations",
        sa.Column("response_classification", sa.Text(), nullable=False),
    )
    op.add_column(
        "answer_evaluations", sa.Column("difficulty_at_time", sa.Text(), nullable=False)
    )
    op.add_column(
        "answer_evaluations", sa.Column("nudge_given", sa.Boolean(), nullable=False)
    )
    op.drop_index("ix_answer_evaluations_turn_number", table_name="answer_evaluations")
    op.drop_constraint(
        "uq_answer_evaluations_candidate_assessment_turn_number",
        "answer_evaluations",
        type_="unique",
    )
    op.create_index(
        op.f("ix_answer_evaluations_section"),
        "answer_evaluations",
        ["section"],
        unique=False,
    )
    op.create_index(
        op.f("ix_answer_evaluations_session_id"),
        "answer_evaluations",
        ["session_id"],
        unique=False,
    )
    op.drop_constraint(
        "answer_evaluations_candidate_assessment_id_fkey",
        "answer_evaluations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "answer_evaluations",
        "interview_sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "interview_evaluations", sa.Column("session_id", sa.UUID(), nullable=False)
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "section_summaries",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "violation_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_constraint(
        "uq_interview_evaluations_candidate_assessment_id",
        "interview_evaluations",
        type_="unique",
    )
    op.drop_index(
        "ix_interview_evaluations_candidate_assessment_id",
        table_name="interview_evaluations",
    )
    op.create_index(
        op.f("ix_interview_evaluations_candidate_assessment_id"),
        "interview_evaluations",
        ["candidate_assessment_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_interview_evaluations_hiring_recommendation"),
        "interview_evaluations",
        ["hiring_recommendation"],
        unique=False,
    )
    op.create_unique_constraint(None, "interview_evaluations", ["session_id"])
    op.drop_constraint(
        "interview_evaluations_candidate_assessment_id_fkey",
        "interview_evaluations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "interview_evaluations",
        "interview_sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "interview_sessions",
        sa.Column("current_section_index", sa.Integer(), nullable=False),
    )
    op.add_column(
        "interview_sessions",
        sa.Column("current_question_text", sa.Text(), nullable=True),
    )
    op.add_column(
        "interview_sessions", sa.Column("current_difficulty", sa.Text(), nullable=False)
    )
    op.add_column(
        "interview_sessions",
        sa.Column("consecutive_strong_answers", sa.Integer(), nullable=False),
    )
    op.add_column(
        "interview_sessions",
        sa.Column("consecutive_weak_answers", sa.Integer(), nullable=False),
    )
    op.add_column(
        "interview_sessions",
        sa.Column(
            "used_concepts",
            postgresql.ARRAY(sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "interview_sessions", sa.Column("silence_attempt", sa.Integer(), nullable=False)
    )
    op.add_column(
        "interview_sessions",
        sa.Column("nudge_given_this_turn", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "interview_sessions",
        sa.Column("irrelevant_strike_count", sa.Integer(), nullable=False),
    )
    op.add_column(
        "interview_sessions",
        sa.Column(
            "violations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.add_column(
        "interview_sessions",
        sa.Column("auto_submit_triggered", sa.Boolean(), nullable=False),
    )
    op.alter_column(
        "interview_sessions",
        "status",
        existing_type=sa.TEXT(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "interview_sessions",
        "current_section",
        existing_type=sa.TEXT(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "interview_sessions",
        "total_elapsed_secs",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "interview_sessions",
        "total_pause_secs",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(
        "uq_interview_sessions_candidate_assessment_id",
        "interview_sessions",
        type_="unique",
    )
    op.drop_index(
        "ix_interview_sessions_candidate_assessment_id", table_name="interview_sessions"
    )
    op.create_index(
        op.f("ix_interview_sessions_candidate_assessment_id"),
        "interview_sessions",
        ["candidate_assessment_id"],
        unique=True,
    )
    op.drop_constraint(
        "interview_sessions_candidate_assessment_id_fkey",
        "interview_sessions",
        type_="foreignkey",
    )
    op.add_column(
        "transcript_turns", sa.Column("session_id", sa.UUID(), nullable=False)
    )
    op.add_column(
        "transcript_turns",
        sa.Column("response_classification", sa.Text(), nullable=True),
    )
    op.add_column(
        "transcript_turns", sa.Column("difficulty_at_time", sa.Text(), nullable=True)
    )
    op.drop_constraint(
        "uq_transcript_turns_candidate_assessment_turn_number",
        "transcript_turns",
        type_="unique",
    )
    op.create_index(
        op.f("ix_transcript_turns_section"),
        "transcript_turns",
        ["section"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcript_turns_session_id"),
        "transcript_turns",
        ["session_id"],
        unique=False,
    )
    op.drop_constraint(
        "transcript_turns_candidate_assessment_id_fkey",
        "transcript_turns",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "transcript_turns",
        "interview_sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transcript_turns", type_="foreignkey")
    op.create_foreign_key(
        "transcript_turns_candidate_assessment_id_fkey",
        "transcript_turns",
        "candidate_assessments",
        ["candidate_assessment_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_index(op.f("ix_transcript_turns_session_id"), table_name="transcript_turns")
    op.drop_index(op.f("ix_transcript_turns_section"), table_name="transcript_turns")
    op.create_unique_constraint(
        "uq_transcript_turns_candidate_assessment_turn_number",
        "transcript_turns",
        ["candidate_assessment_id", "turn_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("transcript_turns", "difficulty_at_time")
    op.drop_column("transcript_turns", "response_classification")
    op.drop_column("transcript_turns", "session_id")
    op.create_foreign_key(
        "interview_sessions_candidate_assessment_id_fkey",
        "interview_sessions",
        "candidate_assessments",
        ["candidate_assessment_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_index(
        op.f("ix_interview_sessions_candidate_assessment_id"),
        table_name="interview_sessions",
    )
    op.create_index(
        "ix_interview_sessions_candidate_assessment_id",
        "interview_sessions",
        ["candidate_assessment_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_interview_sessions_candidate_assessment_id",
        "interview_sessions",
        ["candidate_assessment_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "interview_sessions",
        "total_pause_secs",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "interview_sessions",
        "total_elapsed_secs",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "interview_sessions",
        "current_section",
        existing_type=sa.TEXT(),
        server_default=sa.text("'self_intro'::text"),
        existing_nullable=False,
    )
    op.alter_column(
        "interview_sessions",
        "status",
        existing_type=sa.TEXT(),
        server_default=sa.text("'INITIALIZING'::text"),
        existing_nullable=False,
    )
    op.drop_column("interview_sessions", "auto_submit_triggered")
    op.drop_column("interview_sessions", "violations")
    op.drop_column("interview_sessions", "irrelevant_strike_count")
    op.drop_column("interview_sessions", "nudge_given_this_turn")
    op.drop_column("interview_sessions", "silence_attempt")
    op.drop_column("interview_sessions", "used_concepts")
    op.drop_column("interview_sessions", "consecutive_weak_answers")
    op.drop_column("interview_sessions", "consecutive_strong_answers")
    op.drop_column("interview_sessions", "current_difficulty")
    op.drop_column("interview_sessions", "current_question_text")
    op.drop_column("interview_sessions", "current_section_index")
    op.drop_constraint(None, "interview_evaluations", type_="foreignkey")
    op.create_foreign_key(
        "interview_evaluations_candidate_assessment_id_fkey",
        "interview_evaluations",
        "candidate_assessments",
        ["candidate_assessment_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(None, "interview_evaluations", type_="unique")
    op.drop_index(
        op.f("ix_interview_evaluations_hiring_recommendation"),
        table_name="interview_evaluations",
    )
    op.drop_index(
        op.f("ix_interview_evaluations_candidate_assessment_id"),
        table_name="interview_evaluations",
    )
    op.create_index(
        "ix_interview_evaluations_candidate_assessment_id",
        "interview_evaluations",
        ["candidate_assessment_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_interview_evaluations_candidate_assessment_id",
        "interview_evaluations",
        ["candidate_assessment_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("interview_evaluations", "violation_summary")
    op.drop_column("interview_evaluations", "section_summaries")
    op.drop_column("interview_evaluations", "session_id")
    op.drop_constraint(None, "answer_evaluations", type_="foreignkey")
    op.create_foreign_key(
        "answer_evaluations_candidate_assessment_id_fkey",
        "answer_evaluations",
        "candidate_assessments",
        ["candidate_assessment_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_index(
        op.f("ix_answer_evaluations_session_id"), table_name="answer_evaluations"
    )
    op.drop_index(
        op.f("ix_answer_evaluations_section"), table_name="answer_evaluations"
    )
    op.create_unique_constraint(
        "uq_answer_evaluations_candidate_assessment_turn_number",
        "answer_evaluations",
        ["candidate_assessment_id", "turn_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        "ix_answer_evaluations_turn_number",
        "answer_evaluations",
        ["turn_number"],
        unique=False,
    )
    op.drop_column("answer_evaluations", "nudge_given")
    op.drop_column("answer_evaluations", "difficulty_at_time")
    op.drop_column("answer_evaluations", "response_classification")
    op.drop_column("answer_evaluations", "session_id")
    # ### end Alembic commands ###
